#!/bin/bash

java -Xmx16g -cp target/deform-0.0.2-SNAPSHOT.jar org.janelia.saalfeldlab.deform.DeformFromAligned \
 -i /groups/saalfeld/saalfeldlab/cremi/2016-09-08/sample_C+_padded_20161003.aligned.hdf \
 -j /nrs/saalfeld/heinrichl/synapses/cremi_all_1213_01/prediction_cremi_warped_sampleC+_160000.n5 \
 -l /syncleft_dist \
 --labelssourceoffset 0,0,0 \
 -o /groups/saalfeld/saalfeldlab/cremi/submissions/deform/clefts/sample_C+.clefts.160000.0.1.backwarped.hdf \
 -t /groups/saalfeld/saalfeldlab/cremi/submissions/deform/sample_C+.transforms.json \
 -r 40,4,4 \
 --targetoffset 37,911,911 \
 --transformsize 200,3072,3072 \
 --targetsize 125,1250,1250 \
 -c 64 \
 -x 0.15

